# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T07:36:03+00:00

from __future__ import annotations

from typing import Union

from pydantic import RootModel

from . import (
    MessageStatusMessenger,
    MessageStatusMMS,
    MessageStatusSMS,
    MessageStatusViber,
    MessageStatusWhatsApp,
)


class BodyCallbackPostRequest(
    RootModel[
        Union[
            MessageStatusSMS,
            MessageStatusMMS,
            MessageStatusWhatsApp,
            MessageStatusMessenger,
            MessageStatusViber,
        ]
    ]
):
    root: Union[
        MessageStatusSMS,
        MessageStatusMMS,
        MessageStatusWhatsApp,
        MessageStatusMessenger,
        MessageStatusViber,
    ]
